name: cd

on:
  push:
    branches: 
      - main

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push for PHP5
        uses: docker/build-push-action@v4
        with:
          context: ./docker/php5/
          file: ./docker/php5/Dockerfile
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}:php56, ghcr.io/${{ github.repository }}:php5
      -
        name: Build and push for PHP7
        uses: docker/build-push-action@v4
        with:
          context: ./docker/php7/
          file: ./docker/php7/Dockerfile
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}:php74, ghcr.io/${{ github.repository }}:php7

      -
        name: Build and push for PHP8
        uses: docker/build-push-action@v4
        with:
          context: ./docker/php8/
          file: ./docker/php8/Dockerfile
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}:php82, ghcr.io/${{ github.repository }}:php8
